# vim: ft=yaml sw=2 ts=2

language: go

# create test database
before_install:
  - go get github.com/mattn/goveralls

# go versions to test
go:
  - "1.15.x"
  - "1.16.x"

# run tests w/ coverage
script:
  - travis_retry $GOPATH/bin/goveralls -service=travis-ci
